# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest
  name: "Default"
  environment: Build Environment

steps:
- task: RunWorkflow@2
  inputs:
    gh: 'jeremykodekloud'
    repo: 'jeremykodekloud/arweb'
    workflow: 'testandbuild'
    ref: 'main'


- task: RunWorkflow@2
  inputs:
    gh: 'jeremykodekloud'
    repo: 'jeremykodekloud/arweb'
    workflow: 'Node.js Package'
    ref: 'main'

    
  